import Foundation
import AppKit

// ClipKeepWarm — re-publish the clipboard unchanged, to make the Mac announce
// it again and keep the peer link with the iPad warm.
//
// Mac -> iPad has no prefetch (iOS runs no code at copy time), so every paste
// there is a cold fetch: find the Mac, establish a session, pull the bytes.
// When the link has gone idle that can hang, which is the "stuck loading, then
// works on retry" symptom. Re-announcing costs a BLE advertisement; the data
// itself still only moves when someone actually pastes.
//
// Every flavour is preserved. Rewriting only the plain text would silently
// destroy styling, HTML and image representations.

let concealed: Set<String> = [
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
    "de.petermaurer.TransientPasteboardType",
]

// Promise types must not be materialised here: doing so can pull unbounded
// data, and rewriting them as concrete bytes changes what the clipboard is.
let skipPrefixes = ["com.apple.NSFilePromise", "com.apple.pasteboard.promised"]

let pb = NSPasteboard.general
guard let types = pb.types, !types.isEmpty else { exit(1) }

let names = Set(types.map { $0.rawValue })
if !names.isDisjoint(with: concealed) { exit(2) }        // never re-publish secrets
if names.contains("com.apple.is-remote-clipboard") { exit(3) }  // came from the iPad; leave it

var payload: [(NSPasteboard.PasteboardType, Data)] = []
for type in types {
    if skipPrefixes.contains(where: { type.rawValue.hasPrefix($0) }) { continue }
    if let data = pb.data(forType: type) { payload.append((type, data)) }
}
guard !payload.isEmpty else { exit(4) }

let before = pb.changeCount
pb.clearContents()
pb.declareTypes(payload.map { $0.0 }, owner: nil)
for (type, data) in payload { pb.setData(data, forType: type) }

let total = payload.reduce(0) { $0 + $1.1.count }
print("re-announced \(payload.count) type(s), \(total)B, changeCount \(before) -> \(pb.changeCount)")
