import Foundation
import AppKit
import ApplicationServices
import CryptoKit

// ClipPrefetch — forces macOS to materialise an incoming Universal Clipboard
// payload as soon as it is advertised, instead of lazily at paste time, and
// keeps a local history so a failed paste is always recoverable.

let fm = FileManager.default
let support = fm.homeDirectoryForCurrentUser
    .appendingPathComponent("Library/Application Support/ClipBridge")
let histDir = support.appendingPathComponent("history")
let logURL  = support.appendingPathComponent("prefetch.log")
let latestURL = support.appendingPathComponent("latest.txt")
try? fm.createDirectory(at: histDir, withIntermediateDirectories: true)

let maxHistory = 300
let pollInterval = 0.35

// Markers used by password managers / transient tooling to say "do not record".
let concealedMarkers: Set<String> = [
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
    "de.petermaurer.TransientPasteboardType",
]

// Apple tags a pasteboard that arrived from another device with this type.
let remoteMarker = "com.apple.is-remote-clipboard"

// Types worth forcing across the wire: text, formatted text, and images.
//
// .rtf and .html are what preserve bold, links, lists and colour when
// pasting formatted text — dropping them would flatten every paste to plain.
//
// .tiff is deliberately excluded. An iPad image copy advertises both PNG and
// TIFF, and the TIFF ran a measured 11.6 MB against ~1 MB for the same PNG,
// so prefetching both pulled roughly 12 MB over Wi-Fi per copy whether or not
// it was ever pasted. PNG alone covers the paste. Anything still wanting TIFF
// falls back to a lazy fetch at paste time, exactly as before.
//
// File-promise types are excluded too: materialising them can pull an
// unbounded amount of data.
let prefetchTypes: [NSPasteboard.PasteboardType] = [
    .string,   // plain text
    .rtf,      // formatted text — keeps styling
    .html,     // formatted text from the web
    .URL,      // links
    .png,      // screenshots, and most copies out of Safari
    NSPasteboard.PasteboardType("public.jpeg"),  // photos
    NSPasteboard.PasteboardType("public.heic"),  // photos, iOS default camera format
    NSPasteboard.PasteboardType("public.heif"),
    // public.plain-text is NOT the same UTI as .string (public.utf8-plain-text).
    // Clips from the iPad frequently carry only this one, and reading just
    // .string reported them as empty when they were not.
    NSPasteboard.PasteboardType("public.plain-text"),
]

// Fallbacks, tried only when none of the above yielded anything. public.tiff
// is excluded from the list above because an iPad image copy usually offers
// PNG alongside an 11.6 MB TIFF -- but some clips offer only the TIFF or the
// legacy alias, and those were being discarded as empty.
let fallbackTypes: [NSPasteboard.PasteboardType] = [
    NSPasteboard.PasteboardType("Apple PNG pasteboard type"),
    NSPasteboard.PasteboardType("public.tiff"),
    NSPasteboard.PasteboardType("NeXT TIFF v4.0 pasteboard type"),
]


// Auto-paste. When a clip arrives from the iPad, issue a Cmd-V so it lands in
// whatever is focused. Off unless the flag file exists: pasting into an
// arbitrary frontmost window is not always safe, and a multi-line clip landing
// in a terminal can execute. Requires Accessibility, which is why the daemon
// ships inside an .app bundle -- TCC identifies clients by bundle, not by path.
let autopasteFlag = support.appendingPathComponent("autopaste")


// A banner when something is pasted for you. Auto-paste acts without being
// asked, so it should say what it did -- otherwise text appears in a field
// with no explanation of where it came from.
func notify(_ body: String, title: String = "Pasted from iPad", sound: String? = nil) {
    func esc(_ t: String) -> String {
        t.replacingOccurrences(of: "\\", with: "\\\\")
         .replacingOccurrences(of: "\"", with: "\\\"")
    }
    // A failure has to be distinguishable at a glance from a success, so it
    // gets a different title, a warning mark and a sound. Notification banners
    // have no colour control, so the mark and the sound do that work.
    var script = "display notification \"\(esc(body))\" with title \"\(esc(title))\""
    if let sound { script += " sound name \"\(esc(sound))\"" }
    let task = Process()
    task.executableURL = URL(fileURLWithPath: "/usr/bin/osascript")
    task.arguments = ["-e", script]
    try? task.run()
}

func previewOf(_ pb: NSPasteboard, bytes: Int) -> String {
    if let text = pb.string(forType: .string), !text.isEmpty {
        let flat = text.replacingOccurrences(of: "\n", with: " ")
                       .trimmingCharacters(in: .whitespacesAndNewlines)
        return flat.count > 60 ? String(flat.prefix(60)) + "..." : flat
    }
    let kb = bytes / 1024
    return kb >= 1024 ? "Image, \(kb / 1024) MB" : "Image, \(kb) KB"
}

var lastAutopasteDigest = ""

// Clips copied on this Mac, with the time they were seen. A clip sent to the
// iPad is announced straight back, and arrives here looking like a clip FROM
// the iPad -- so without this, auto-paste pastes your own clipboard at you.
var recentLocalDigests: [(digest: String, seen: Date)] = []

func autopasteEnabled() -> Bool {
    FileManager.default.fileExists(atPath: autopasteFlag.path)
}

func accessibilityGranted(prompt: Bool) -> Bool {
    let key = kAXTrustedCheckOptionPrompt.takeUnretainedValue() as String
    return AXIsProcessTrustedWithOptions([key: prompt] as CFDictionary)
}

func pressCommandV() -> Bool {
    guard accessibilityGranted(prompt: false) else { return false }
    let source = CGEventSource(stateID: .combinedSessionState)
    let vKey: CGKeyCode = 9
    guard let keyDown = CGEvent(keyboardEventSource: source, virtualKey: vKey, keyDown: true),
          let keyUp   = CGEvent(keyboardEventSource: source, virtualKey: vKey, keyDown: false)
    else { return false }
    keyDown.flags = .maskCommand
    keyUp.flags = .maskCommand
    keyDown.post(tap: .cghidEventTap)
    keyUp.post(tap: .cghidEventTap)
    return true
}

let isoFmt: ISO8601DateFormatter = {
    let f = ISO8601DateFormatter()
    f.formatOptions = [.withInternetDateTime]
    return f
}()

func log(_ message: String) {
    let line = "[\(isoFmt.string(from: Date()))] \(message)\n"
    if let data = line.data(using: .utf8) {
        if let handle = try? FileHandle(forWritingTo: logURL) {
            handle.seekToEndOfFile()
            handle.write(data)
            try? handle.close()
        } else {
            try? data.write(to: logURL)
        }
    }
    FileHandle.standardOutput.write(line.data(using: .utf8)!)
}

func pruneHistory() {
    guard let files = try? fm.contentsOfDirectory(
        at: histDir, includingPropertiesForKeys: [.contentModificationDateKey]
    ) else { return }
    guard files.count > maxHistory else { return }
    let sorted = files.sorted {
        let a = (try? $0.resourceValues(forKeys: [.contentModificationDateKey]).contentModificationDate) ?? .distantPast
        let b = (try? $1.resourceValues(forKeys: [.contentModificationDateKey]).contentModificationDate) ?? .distantPast
        return a < b
    }
    for url in sorted.prefix(files.count - maxHistory) {
        try? fm.removeItem(at: url)
    }
}

func handleChange(_ pb: NSPasteboard, changeCount: Int) {
    let start = Date()
    guard let types = pb.types, !types.isEmpty else {
        log("change \(changeCount): pasteboard empty")
        return
    }
    let names = Set(types.map { $0.rawValue })
    let isRemote = names.contains(remoteMarker)
    let isConcealed = !names.isDisjoint(with: concealedMarkers)

    // Force the transfer. Reading the data is what makes a promised /
    // remote payload actually come across the link.
    var fetched = 0
    var fetchedTypes: [String] = []
    var hasher = SHA256()
    for type in prefetchTypes where types.contains(type) {
        if let data = pb.data(forType: type) {
            fetched += data.count
            hasher.update(data: data)
            fetchedTypes.append("\(type.rawValue)=\(data.count)B")
        }
    }
    // Nothing from the primary list? The clip may still carry content under a
    // legacy or alternative type. This is what "0B empty" actually was.
    if fetched == 0 {
        for type in fallbackTypes where types.contains(type) {
            if let data = pb.data(forType: type), !data.isEmpty {
                fetched += data.count
                hasher.update(data: data)
                fetchedTypes.append("\(type.rawValue)=\(data.count)B(fallback)")
                break
            }
        }
    }

    // Universal Clipboard re-advertises the iPad's existing clipboard every
    // so often, and each re-advertisement bumps changeCount -- so identical
    // content arrives repeatedly. Fingerprint it, or auto-paste fires again
    // for a clip that was never re-copied.
    let digest = hasher.finalize().map { String(format: "%02x", $0) }.joined()
    let elapsedMs = Int(Date().timeIntervalSince(start) * 1000)
    let origin = isRemote ? "REMOTE" : "local"

    // Anything advertised that we chose not to pull. public.tiff is expected
    // here; an unfamiliar image format showing up means the list above needs
    // widening, and would otherwise only reveal itself as a slow paste.
    let skipped = names
        .subtracting(prefetchTypes.map { $0.rawValue })
        .subtracting([remoteMarker])
        .sorted()

    // 0 recoveries in 9 attempts, and the wait blinded the poll loop for
    // seven seconds each time. The payload does not arrive late; it does not
    // arrive at all.
    // A hollow announcement cannot be repaired here: the payload never
    // existed. The only useful thing left is to say so immediately, so the
    // failure is known at once rather than discovered by pasting nothing.
    let recovery = (isRemote && fetched == 0) ? " HOLLOW" : ""
    if isRemote && fetched == 0 && !names.contains("com.apple.is-remote-clipboard-empty") {
        notify("Copy it again on the iPad — nothing came through",
               title: "🔴 CLIPBOARD FAILED", sound: "Basso")
    }
    log("change \(changeCount) [\(origin)] \(elapsedMs)ms \(fetched)B\(recovery) "
        + "got=[\(fetchedTypes.joined(separator: " "))]"
        + " skipped=[\(skipped.joined(separator: " "))]"
        + (isConcealed ? " (concealed - not stored)" : ""))

    // Only clips from the iPad, only when they carried something, never a
    // password-manager clip.
    // Images auto-paste too. The five duplicate pastes that looked like a
    // conflict with dictation were one image re-announced five times by the
    // iPad, not an image problem -- the fingerprint check below is what stops
    // that, so the content type does not need restricting.
    // Remember local clips; forget them after two minutes.
    if !isRemote && !digest.isEmpty && fetched > 0 {
        recentLocalDigests.append((digest, Date()))
    }
    recentLocalDigests.removeAll { Date().timeIntervalSince($0.seen) > 120 }
    let isEcho = isRemote && !digest.isEmpty
        && recentLocalDigests.contains { $0.digest == digest }

    let isRepeat = isRemote && !digest.isEmpty && digest == lastAutopasteDigest
    if isRemote && fetched > 0 && !isConcealed && autopasteEnabled() {
        if isEcho {
            lastAutopasteDigest = digest
            log("autopaste: skipped - echo of a clip copied on this Mac")
        } else if isRepeat {
            log("autopaste: skipped - the iPad re-announced the same clip")
        } else {
            Thread.sleep(forTimeInterval: 0.15)   // let the pasteboard settle
            if pressCommandV() {
                lastAutopasteDigest = digest
                let preview = previewOf(pb, bytes: fetched)
                notify(preview)
                log("autopaste: pasted into the focused window — \(preview)")
            } else {
                log("autopaste: BLOCKED - Accessibility not granted to ClipBridgeAgent")
            }
        }
    } else if isRemote && fetched > 0 && !digest.isEmpty {
        lastAutopasteDigest = digest   // track it even while autopaste is down
    }

    guard !isConcealed else { return }
    guard let text = pb.string(forType: .string), !text.isEmpty else { return }

    // Identical to the previous clip? Do not add another history entry. The
    // keep-warm re-announces the current clipboard unchanged every few
    // minutes, which would otherwise bury real clips under duplicates.
    if let previous = try? String(contentsOf: latestURL, encoding: .utf8), previous == text {
        return
    }

    try? text.write(to: latestURL, atomically: true, encoding: .utf8)
    let stamp = isoFmt.string(from: Date()).replacingOccurrences(of: ":", with: "-")
    let entry = histDir.appendingPathComponent("\(stamp)-\(changeCount).txt")
    try? text.write(to: entry, atomically: true, encoding: .utf8)
    pruneHistory()
}

log("ClipPrefetch started (poll \(pollInterval)s, history cap \(maxHistory))")

// If auto-paste is on but Accessibility is not granted, ask for it here. The
// system dialog identifies this bundle and adds it to the list on approval,
// which is far more reliable than adding it by hand in Finder -- and a grant
// made while this process is already running is not picked up until restart.
if autopasteEnabled() {
    if accessibilityGranted(prompt: true) {
        log("autopaste: Accessibility granted")
    } else {
        log("autopaste: Accessibility NOT granted - approve the dialog, then run: clip reload")
    }
}
let pb = NSPasteboard.general
var lastCount = pb.changeCount
log("baseline changeCount=\(lastCount)")

while true {
    let current = pb.changeCount
    if current != lastCount {
        lastCount = current
        handleChange(pb, changeCount: current)
    }
    Thread.sleep(forTimeInterval: pollInterval)
}
